version: '3.8'

services:
  app:
    build: .
    container_name: mailsender
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      URL: jdbc:postgresql://db:5432/contactdb
      USERNAME: postgres
      PASSWORD: password

  db:
    image: postgres:15
    container_name: contactdb
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
